import { 
  vanLife1,
  vanLife2,
  vanLife3,
  vanLife4,
  Quizzical1,
  Quizzical2,
  Tenzies1,
  Tenzies2,
  Guides1,
  Guides2,
  Guides3,
  ORGuides1,
  ORGuides2,
  ORGuides3,
  ORGuides4,
  table1,
  table2,
  table3,
  table4 
} from "./assets/images"

export const projectInfo = [
  {id: 1, name: "VanLife", description:"VanLife was created as part of the Scrimba.com Front End Developer Career Path. The concept is something of a VRBO, but for Vans, rather than properties. There's a 'shopper' experience as well as a 'renter' experience. The primary goal was created was learning about React Router, but it also reinforced a number of different basic React concepts.", source: "https://github.com/jasnmar/scrimba-ar-vanLife", image: "https://jasonsstorage.s3.amazonaws.com/vanLife.png", deploy: "https://jason-scrimba-vanlife.netlify.app/", goals: ["Browser Router", "Routes", "Links", "Route Params", "Nested Routes", "Layout Routes", "Outlets", "Outlet Context", "Search / Query Params", "Use Location (and state)", "Router Provider", "Loader", "ErrorElement", "Protected Routes", "UseLoaderData, UseActionData", "UseNavigation"], images: [{image: vanLife1, link: "https://jason-scrimba-vanlife.netlify.app/about"}, {image: vanLife2, link: "https://jason-scrimba-vanlife.netlify.app/vans"}, {image: vanLife3, link: "https://jason-scrimba-vanlife.netlify.app/host/vans"}, {image: vanLife4, link: "https://jason-scrimba-vanlife.netlify.app/host/vans/1"}] },
  {id: 2, name: "Quizzical", description:"Quizzical was done at the end of the React Basics course as part of the Scrimba.com Front End Developer Carrer Path. I used question components to build the quiz itself, all of the quiz data comes from the opentrivia DB.", source: "https://github.com/jasnmar/scrimba-rb-quizzical", image: "https://jasonsstorage.s3.amazonaws.com/quizzical.png", deploy: "https://quizzical-squirel.netlify.app/", images: [{image: Quizzical1}, {image: Quizzical2}] ,goals: ["React", "React Components", "Managing State", "Fetching Data"]},
  {id: 3, name: "Tensies", description: "A simple number matching game with dice that tracks the lowest score. It uses local storage to keep track of the lowest score achieved. Each of the die are React Components.", source: "https://github.com/jasnmar/scrimba-rb-tensies", image: "https://jasonsstorage.s3.us-east-1.amazonaws.com/Tensies.png", deploy: "https://glistening-semifreddo-a079a1.netlify.app/", images: [{image: Tenzies1}, {image: Tenzies2}], goals:["Component Reuse (Die)", "Arrays of Components", "Managing Component State", "Managing State"]},
  {id: 4, name: "Logbook", description: "Created to assist the guides at Bronco Off-Roadeo. To better understand how much experience we have as guides we are required to keep logbooks of the time we spend instructing, off-roading, training etc. Also, if we want to get paid, we are required to fill out a time sheet and submit an invoice. These 3 tasks had been completely separate from one another. This litte app combines those three tasks, so as long as you fill out your logbook your invoice and timesheet are generated for you. It is intended as a mobile first experience, so that guides can quickly (30 seconds) log their work for the day when they get back to basecamp from their phones. I wrote this before I had taken any formal web dev courses, so it's an interesting mixture of things.", images: [{image: Guides1}, {image: Guides2}, {image: Guides3}],goals: ["Node", "Bootstrap", "Handlebars", "Express", "REST APIs"]},
  {id: 5, name: "Off-Roadeo Guides", description: "Assists past Bronco Off-roadeo guests by providing them with a way to refresh themselves after their day at Bronco Off-Roadeo. We commonly get questions about whether or not the information we go through during the day is available somewhere other than what we talke about during the day itself. This is a solution to that.", images: [{image: ORGuides1}, {image: ORGuides2}, {image: ORGuides3}, {image: ORGuides4}],goals: ["React", "Typescript", "React Router"], source: "https://github.com/jasnmar/guides-home", deploy:"https://www.offroadeoguides.com"},
  {id: 6, name: "Live Edge Wood and Epoxy Table", description:"From start to finish this project took roughtly 3 years. It took a little over 2 years for the wood, that when I first encountered it was in the form of a standing tree, to dry enough to use in a project. Then there was a few months working in the basement pouring a layer of epoxy, then waiting 24 hours for it to dry. Finally finishing took probably at least a few weeks starting with 40 grit sandpaper and working all the way up to 2000 grit.", images:[{image: table1}, {image: table2}, {image: table3}, {image: table4}]}
]

export const jobInfo = [
  {id: 1, employer: "Bronco Off-Roadeo", employerLink: "www.broncooffroadeo.com", position:"Instructor", location:"Gilford NH", description: ["Act as the key point of contact, guiding Bronco Off-Roadeo guests through their immersive off-road learning adventure. Build trust with guests so that they are comfortable driving in very unusual situations. Provide guests with off-road driving instruction and assistance including real time feedback and verifying they are proceeding safely. Ensure guests are having fun learning the capabilities of their vehicles and introducing them to techniques particular to off-roading.", "Work with other Instructors to prepare the vehicles for the day, as well as plan out the routes we will be using that day. React to what happens out on trail, while maintaining the overall schedule of the day."], startDate:"2023", endDate:"Present"},
  {id: 2, employer: "Meltwater", position:"Agile Coach", location:"Manchester NH", description: "Led daily ceremonies of up to five concurrent teams. Coordinated company-wide initiatives, such as the Front-End Guild, which were both regular meetings and strategic off-site events. Facilitated UX Design Review meetings to improve efficiency. Created and implemented the 'Meltwater Maturity Matrix,' enabling teams to understand and optimize their Agile practices. ", bullets: ["Led Team launch and re-launch events.", "Mentored junior coaches.", "Built statistical analysis applications using Jira data."], startDate:"2018", endDate:"2023"},
  {id: 3, employer: "Autodesk", position:"Agile Coach", location: "Manchester NH", startDate:"2014", endDate:"2018", description: "Executed implementation and advancement of a unified agile framework across our division, encompassing up to 35 teams distributed across the US, Europe, and Asia. Involved in establishing standardized scrum ceremonies, optimal sprint durations, effective utilization of agile tools, clear definitions of completion, and collaborative team accords. Collaborated with individual teams to detect and rectify counterproductive practices, offering tailored recommendations for enhancements that align with consistent reinforcement of agile principles and values. ", bullets: ["Guided facilitation of Agile Maturity Team Assessments, empowering teams to cultivate enduring positive behaviors." , "Crafted and provided diverse training modules, spanning Team, Product Owner, Scrum Master, and Agile Refresher courses.", "Orchestrated Epic Definition workshops involving teams and stakeholders, fostering comprehension of envisioned outcomes.",  "Instituted dedicated communities of practice for Product Owners and Scrum Masters, fostering exchange of insights and methodologies to collaboratively troubleshoot challenges."]},
  {id: 4, employer: "Autodesk", position: "User Experience Manager / Agile Coach", startDate:"2010", endDate:"20214", location: "Manchester NH", description: "Led an international team of Product Owners and UX Designers, driving the development of core Architecture/Engineering/Construction products. Fostered strong collaboration with Product Management to define team objectives and address critical software challenges. Partnered with functional leaders to assemble skilled teams, ensuring efficient product release cycles. Established clear requirement communication protocols in collaboration with Product Management, optimizing the development process.", bullets: ["Acted as Agile Coach for many teams, guiding their agile processes.", "Pioneered inception of a Scrum Master's Practice group to foster discussions on agile matters and team dynamics.","Offered consultation to Teams and Managers, driving enhancements to team processes and workflows for optimal outcomes.", "Examined Research findings, Workflows, and Interfaces put forth by teams on a regular cadence, ensuring uniformity throughout the product line and with other internal offerings.", "Scrutinized Research outcomes, Workflows, and Interfaces presented by User Experience Designers throughout the organization, ensuring uniformity across the product spectrum and with other internal offerings."]}, 
  {id: 5, employer: "Autodesk", position: "User Experience Designer", startDate:"2003", endDate:"2010", location: "Manchester NH", description: "Was the designer for all Mechanical, Electrical and Piping functionality for  Autodesk's Flagship AEC platform, Revit. "}
]

