export const projectInfo = [
  {id: 1, name: "VanLife", description:"VanLife was created as part of the Scrimba.com Front End Developer Career Path. The concept is something of a VRBO, but for Vans, rather than properties. There's a 'shopper' experience as well as a 'renter' experience. The primary goal was created was learning about React Router, but it also reinforced a number of different basic React concepts.", source: "https://github.com/jasnmar/scrimba-ar-vanLife", image: "https://jasonsstorage.s3.amazonaws.com/vanLife.png", deploy: "https://jason-scrimba-vanlife.netlify.app/", goals: ["Browser Router", "Routes", "Links", "Route Params", "Nested Routes", "Layout Routes", "Outlets", "Outlet Context", "Search / Query Params", "Use Location (and state)", "Router Provider", "Loader", "ErrorElement", "Protected Routes", "UseLoaderData, UseActionData", "UseNavigation"] },
  {id: 2, name: "Quizzical", description:"Quizzical was done at the end of the React Basics course as part of the Scrimba.com Front End Developer Carrer Path. I used question components to build the quiz itself, all of the quiz data comes from the opentrivia DB.", source: "https://github.com/jasnmar/scrimba-rb-quizzical", image: "https://jasonsstorage.s3.amazonaws.com/quizzical.png", deploy: "https://quizzical-squirel.netlify.app/"}
]

export const jobInfo = [
  {id: 1, employer: "Bronco Off-Roadeo", employerLink: "www.broncooffroadeo.com", position:"Instructor", location:"Gilford NH", description: ["Act as the key point of contact, guiding Bronco Off-Roadeo guests through their immersive off-road learning adventure. Build trust with guests so that they are comfortable driving in very unusual situations. Provide guests with off-road driving instruction and assistance including real time feedback and verifying they are proceeding safely. Ensure that are having fun learning the capabilities of their vehicles and introducing them to techniques particular to off-roading.", "Work with other Instructors to prepare the vehicles for the day, as well as plan out the routes we will be using that day. React to what happens out on trail, while maintaining the overall schedule of the day."], startDate:"2023", endDate:"Present"},
  {id: 2, employer: "Meltwater", position:"Agile Coach", location:"Manchester NH", description: "Engaged in dynamic blend of hands-on daily team activities, often spanning up to five teams concurrently, alongside broader organizational initiatives. Guide diverse Front-End Guild offsite conferences and collaborative sessions, in addition to regular Front-End Guild gatherings. Commence facilitation of UX Team design review meetings, ensuring streamlined operations and aligned outcomes. Pioneered and introduced custom Agile Maturity Model termed Meltwater Maturity Matrix. Empowered teams to assess and adjust their actions effectively.Attained remarkable accomplishments, including initiating new team launches, providing guidance to junior coaches, and constructing applications to enhance statistical analysis using Jira data.", startDate:"2018", endDate:"2023"},
  {id: 3, employer: "Autodesk", position:"Agile Coach", location: "Manchester NH", startDate:"2014", endDate:"2018", description: "Executed implementation and advancement of a unified agile framework across our division, encompassing up to 35 teams distributed across the US, Europe, and Asia. Involved in establishing standardized scrum ceremonies, optimal sprint durations, effective utilization of agile tools, clear definitions of completion, and collaborative team accords. Collaborated with individual teams to detect and rectify counterproductive practices, offering tailored recommendations for enhancements that align with consistent reinforcement of agile principles and values. ", bullets: ["Guided facilitation of Agile Maturity Team Assessments, empowering teams to cultivate enduring positive behaviors." , "Crafted and provided diverse training modules, spanning Team, Product Owner, Scrum Master, and Agile Refresher courses.", "Orchestrated Epic Definition workshops involving teams and stakeholders, fostering comprehension of envisioned outcomes.",  "Instituted dedicated communities of practice for Product Owners and Scrum Masters, fostering exchange of insights and methodologies to collaboratively troubleshoot challenges."]},
  {id: 4, employer: "Autodesk", position: "User Experience Manager / Agile Coach", startDate:"2010", endDate:"20214", location: "Manchester NH", description: "Led international team comprising Product Owners and User Experience Designers with primary duty of creating our premier Architecture/Engineering/Construction products. Engaged with Product Management to establish precise team expectations by communicating software-related concerns requiring attention. Collaborated with various functional leaders to assemble teams with the competence to deliver anticipated product functionality with each release. Partnered with product management to precisely outline methodologies for relaying requirements to teams.", bullets: ["Took on role of Scrum Master for the teams, guiding their agile processes.", "Pioneered inception of a Scrum Master's Practice group to foster discussions on agile matters and team dynamics.","Offered consultation to Teams and Managers, driving enhancements to team processes and workflows for optimal outcomes.", "Directed an international cohort of User Experience Designers responsible for shaping the design aspects of our premier Architecture/Engineering/Construction products.", "Examined Research findings, Workflows, and Interfaces put forth by teams on a regular cadence, ensuring uniformity throughout the product line and with other internal offerings.", "Scrutinized Research outcomes, Workflows, and Interfaces presented by User Experience Designers throughout the organization, ensuring uniformity across the product spectrum and with other internal offerings."]}, 
  {id: 5, employer: "Autodesk", position: "User Experience Designer", startDate:"2003", endDate:"2010", location: "Manchester NH", description: "Was the designer for all Mechanical, Electrical and Piping functionality for  Autodesk's Flagship AEC platform, Revit. "}
]

