export const projectInfo = [
  {id: 1, name: "VanLife", description:"The VanLife project was created as part of the Scrimba.com Front End Developer Career Path. The primary goal of the section where it was created was learning about React Router, but it also reinforced a number of different React concepts like componentization.", source: "https://github.com/jasnmar/scrimba-ar-vanLife", image: "https://jasonsstorage.s3.amazonaws.com/vanLife.png", deploy: "https://jason-scrimba-vanlife.netlify.app/", goals: ["Browser Router", "Routes", "Links", "Route Params", "Nested Routes", "Layout Routes", "Outlets", "Outlet Context", "Search / Query Params", "Use Location (and state)", "Router Provider", "Loader", "ErrorElement", "Protected Routes", "UseLoaderData, UseActionData", "UseNavigation"] },
  {id: 2, name: "Quizzical", description:"The Quizzical project was done at the end of the React Basics course as part of the Scrimba.com Front End Developer Carrer Path. I used question components to build the quiz itself, all of the quiz data comes from the opentrivia DB.", source: "https://github.com/jasnmar/scrimba-rb-quizzical", image: "https://jasonsstorage.s3.amazonaws.com/quizzical.png", deploy: "https://quizzical-squirel.netlify.app/"}
]

export const jobInfo = [
  {id: 1, employer: "Bronco Off-Roadeo", position:"Instructor", location:"Gilford NH", description: "Provide guests with off-road instruction and guidance; while ensuring they are having fun learning the capabilities of their vehicles as well as introducing them to techniques particular to off-roading. Plan daily “routes” based on early evaluation of group ability and weather conditions but adapt those plans throughout the day based on real time information gained while on trail while communicating with other trail guides so that we don’t have conflicting plans. ", startDate:"May 2023", endDate:"Present"},
  {id: 2, employer: "Meltwater", position:"Agile Coach", location:"Manchester NH", description: "Engaged in dynamic blend of hands-on daily team activities, often spanning up to five teams concurrently, alongside broader organizational initiatives. Guide diverse Front-End Guild offsite conferences and collaborative sessions, in addition to regular Front-End Guild gatherings. Commence facilitation of UX Team design review meetings, ensuring streamlined operations and aligned outcomes. Pioneered and introduced custom Agile Maturity Model termed Meltwater Maturity Matrix. Empowered teams to assess and adjust their actions effectively.Attained remarkable accomplishments, including initiating new team launches, providing guidance to junior coaches, and constructing applications to enhance statistical analysis using Jira data.", startDate:"2018", endDate:"2023"},
]

